# Generated by Django 5.0 on 2025-09-16 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
